#15 Add optional labels and suffix to prometheus metrics.
hivemq/hivemq-prometheus-extension pull request #16
Opened 2021-02-04 23:09 UTC by mhofsche

Motivation

Add optional support for labels and metric name suffix to prometheus metrics from configuration. Can be used to add hostname or IP address to metrics for example. Labels can be used in PromQL queries.

Changes

implement io.prometheus.client.dropwizard.samplebuilder.SampleBuilder to support labels
add optional labels to configuration
add optional suffix to configuration

Example metric:
com_hivemq_jvm_threads_runnable_count_cluster01{host="rivendell",host_ip="127.0.0.1",} 19.0

2021-02-05 09:27 UTC, schaebo commented
@mhofsche The current version of the dependency simpleclient_dropwizard already supports additional labels, maybe this would be better than adding a custom SampleBuilder. I haven't tried it but it would be worth checking out imho.

2021-02-09 21:25 UTC, mhofsche commented
@schaebo  The PR uses the DefaultSampleBuilder of the dependency simpleclient_dropwizard in the custom SampleBuilder to add configured labels and suffix. Did discover and fixed another issue with Histogram and Timer metrics. Quantiles are implemented as labels.

2021-02-10 12:40 UTC, ahelmbr commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    private List<String> combineLists(final List<String> additionalList, final List<String> configList) {
add @NotNull for the configList

2021-02-10 12:41 UTC, ahelmbr commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +            final String[] splitLabels = StringUtils.splitPreserveAllTokens(labels, ";");
could be streamed like 
Stream.of(StringUtils.splitPreserveAllTokens(labels, ";")).forEach(
                    label -> { ... };

2021-02-10 12:50 UTC, ahelmbr reviewed
looks fine for me

2021-02-10 12:50 UTC, ahelmbr commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +            final String dropwizardName,
add @Nullable or @NotNull Annotation

2021-03-06 12:01 UTC, sauroter commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    public Collector.MetricFamilySamples.Sample createSample(
Missing nullability annotation.

2021-03-06 12:01 UTC, sauroter commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    private List<String> combineLists(final @Nullable List<String> additionalList, final @NotNull List<String> configList) {
Missing nullability annotations.

2021-03-06 12:01 UTC, sauroter commented on src/test/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilderTest.java
> +/*
I like the tests.

2021-03-06 12:01 UTC, sauroter requested changes
Comments are inlined.

2021-03-08 22:23 UTC, mhofsche commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    public Collector.MetricFamilySamples.Sample createSample(
added

2021-03-08 22:23 UTC, mhofsche commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    private List<String> combineLists(final @Nullable List<String> additionalList, final @NotNull List<String> configList) {
added

2021-03-09 08:22 UTC, sauroter commented on src/main/java/com/hivemq/extensions/prometheus/export/PrometheusSampleBuilder.java
> +    private @NotNull List<String> combineLists(final @Nullable List<String> additionalList, final @NotNull List<String> configList) {
```suggestion
    private @NotNull List<@NotNull String> combineLists(final @Nullable List<@NotNull String> additionalList, final @NotNull List<@NotNull String> configList) {
```

2021-03-09 08:23 UTC, sauroter approved these changes

2022-10-24 17:04 UTC, closed without merging